version: "3.9"
services:
  database:
    container_name: budgetista-api-db
    image: postgres
    environment:
      POSTGRES_DB: budgetista
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: budgetista-api
    volumes:
      - budgetista-api_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer:latest
    container_name: budgetista-adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    restart: always
    ports:
      - 80:8080

volumes:
  budgetista-api_db:

networks:
  default:
    name: budgetista-api-network
